import subprocess, fileinput




def transforme(chemin_srt):
    chemin_ass = chemin_srt.replace(".srt", ".ass")
    cmd = ["ffmpeg", "-i", chemin_srt, chemin_ass]
    subprocess.run(cmd)
    return chemin_ass



def num_param(parametre):
    parametre = parametre.lower()
    match parametre:
        case "fontname":
            return 1
        case "fontsize":
            return 2
        case "primarycolour":  #on suppose qu'on utilisera pas bcp de param
            return 3
        case "backColour":
            return 6
        case "bold":
            return 7
        case "italic":
            return 8
        case "underline":
            return 9
        case "spacing":
            return 13
        case "angle":
            return 14
        case "borderstyle":
            return 15
        case "outline":
            return 16
        case "shadow":
            return 17
        case "alignment":
            return 18
        case "marginl":
            return 19
        case "marginr":
            return 20
        case "marginv":
            return 21

"""
        On suppose: Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
        Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
        """

def mise_en_forme(chemin_ass, parametre):   #parametre est une liste
    for ligne in fileinput.input(chemin_ass, inplace=True):
        if not ligne.startswith('Style'):
            print(ligne, end = '')   # le end = '' permet d'éviter de faire retour ligne auto du print
        else:
            ligne = ligne.split(",")  # met dans une liste cahque paramètre
            for i in parametre:  # param sous annuaire{param: valeur, ...}
                p = num_param(i)
                ligne[p] = parametre[i]
            ligne = ", ".join(ligne)
            print(ligne, end='')




"""
import fileinput
for line in fileinput.input('1.txt', inplace=1):
 print line,
 if line.startswith('foo1 bar3'):
     print 'foo bar'
"""

"""
        debutrecherche = 0
        for i in range (23): #23 parametre donc 23 virgules
            print(ligne[debutrecherche:].find(",") + 1)
            posDebutp = ligne[debutrecherche:].find(",") + 1 + debutrecherche   #place premier caractere après virgule
            posFinp = ligne[posDebutp:].find(",") - 1 + posDebutp     #place dernier caractère avant virgule (prochain parametre donc)
            print(posFinp, posDebutp)
            parametre = ligne[posDebutp:posFinp + 1]
            print(parametre)
            match i:
                case 0:
                    ligne = ligne.replace(parametre, police,1) # car x0:x1 ca va de x0 à x1-1
                    print(ligne)
                case 1:
                    ligne = ligne.replace(parametre, taille,1)
                    print(ligne)
                case 2:
                    ligne = ligne.replace(parametre, "pomm",1)
                    print(ligne)
                case 3:
                    ligne = ligne.replace(parametre, "Poire", 1)
                    print(ligne)

                case 4:
                    ligne = ligne.replace(parametre, "Poileee", 1)
                    print(ligne)
                    break
            debutrecherche = ligne[posDebutp:].find(",") + posDebutp
            print(debutrecherche)
            
[Script Info]
; Script generated by FFmpeg/Lavc62.11.100
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""




if __name__ == "__main__":
    mise_en_forme(r"C:\Users\ianpa\Documents\PROJET_PERSO\Projet_Sous_titre_film-main\Projet_Sous_titre_film-main\ST_Generes\Stalker_STFR.ass", {"Fontsize": "5", "Fontname": "sans-serif", "MarginV": "40"} )