import subprocess

from typing_extensions import Format


def transforme(chemin_srt):
    chemin_ass = chemin_srt.replace(".srt", ".ass")
    cmd = ["ffmpeg", "-i", chemin_srt, chemin_ass]
    subprocess.run(cmd)
    return chemin_ass

def mise_en_forme(chemin_ass):   #parametre est une liste
    with open(chemin_ass, "r") as f:
        for ligne in f.readlines(): #on parcourt ligne par ligne
            if "Style: " in ligne:          #si on est dans la ligne qui définie les styles
                break
        ligne = ligne.split(",") #met dans une liste cahque paramètre
        for param in parametre:


        print(ligne[])

def num_param(parametre):
    match parametre:
        case "Fontname":
            return 1
        case "Fontsize":
            return 2
        case "PrimaryColour":  #on suppose qu'on utilisera pas bcp de param
            return 3
        case "BackColour":
            return 6
        case "Bold":
            return 7
        case "Italic":
            return 8
        case "Underline":
            return 9
        case "spacing":
            return 13
        case "Angle":
            return 14
        case "BorderStyle":
            return 15
        case "Outline":
            return 16
        case "Shadow":
            return 17
        case "Alignment":
            return 18
        case "MarginL":
            return 19
        case "MarginR":
            return 20
        case "MarginV":
            return 21

        """
        On suppose: Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
        Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1
        """
        # faire une lsite pour les Parametre, plus simple à manipuler, on peut verif. Si None,, alors on fera if None...
        # mettre les truc case dans une fonction faite pour.
        """"
        debutrecherche = 0
        for i in range (23): #23 parametre donc 23 virgules
            print(ligne[debutrecherche:].find(",") + 1)
            posDebutp = ligne[debutrecherche:].find(",") + 1 + debutrecherche   #place premier caractere après virgule
            posFinp = ligne[posDebutp:].find(",") - 1 + posDebutp     #place dernier caractère avant virgule (prochain parametre donc)
            print(posFinp, posDebutp)
            parametre = ligne[posDebutp:posFinp + 1]
            print(parametre)
            match i:
                case 0:
                    ligne = ligne.replace(parametre, police,1) # car x0:x1 ca va de x0 à x1-1
                    print(ligne)
                case 1:
                    ligne = ligne.replace(parametre, taille,1)
                    print(ligne)
                case 2:
                    ligne = ligne.replace(parametre, "pomm",1)
                    print(ligne)
                case 3:
                    ligne = ligne.replace(parametre, "Poire", 1)
                    print(ligne)

                case 4:
                    ligne = ligne.replace(parametre, "Poileee", 1)
                    print(ligne)
                    break
            debutrecherche = ligne[posDebutp:].find(",") + posDebutp
            print(debutrecherche)
"""


"""
[Script Info]
; Script generated by FFmpeg/Lavc62.11.100
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""
if __name__ == "__main__":
    mise_en_forme(r"C:\Users\ianpa\OneDrive - Universite de Lorraine\Documents\PROJET_PERSO\Sous_titre\ST_Generes\Stalker_STFR.ass","Ari", "16" )